# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Favorite Recipe' do

pod 'AFNetworking', '2.2.1'
pod 'Parse'

end

target 'Favorite RecipeTests' do

end

